version: '3.1'
services:
  nginx:
    image: nginx:1.17.2-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - myapp
    ports:
      - "8989:8989"
  myapp:
    build: ./app
    container_name: myapplication
    restart: always
    volumes:
      - ${LOG_PATH_HOST}:${LOG_PATH_CONTAINER}
    environment:
      POSTGRES_HOST: pgdb # переменная для приложения
    ports:
      - "3000:3000"
    depends_on:
      - pgdb
  pgdb:
    image: postgres:11.4-alpine
    container_name: mypostgresdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      PGDARA: ${DB_PATH_POSTGRES}
    volumes:
      - ${DB_PATH_HOST}:${DB_PATH_POSTGRES}
volumes:
  pgdbdata: null